"""Shared profile-only compact rollout mode constants."""

COMPACT_ROLLOUT_SLAB_ACTION_MODE_SEARCH_FEEDBACK = "search_feedback"
COMPACT_ROLLOUT_SLAB_ACTION_MODE_SCRIPTED_RANDOM = "scripted_random"
COMPACT_ROLLOUT_SLAB_ACTION_MODES = (
    COMPACT_ROLLOUT_SLAB_ACTION_MODE_SEARCH_FEEDBACK,
    COMPACT_ROLLOUT_SLAB_ACTION_MODE_SCRIPTED_RANDOM,
)
