"""Conservative scaled Modal trainer attempt for LightZero MuZero dummy Pong.

This keeps the tiny smoke entrypoint tiny while reusing its run-management,
checkpoint mirroring, and env-side telemetry plumbing.
"""

from __future__ import annotations

import json
from typing import Any

import modal

from curvyzero.infra.modal.lightzero_dummy_pong_config_import_smoke import (
    DEFAULT_BATCH_SIZE,
    DEFAULT_COLLECTOR_ENV_NUM,
    DEFAULT_ENV,
    DEFAULT_EVALUATOR_ENV_NUM,
    DEFAULT_EPS_DECAY,
    DEFAULT_EPS_END,
    DEFAULT_EPS_GREEDY_EXPLORATION_IN_COLLECT,
    DEFAULT_EPS_START,
    DEFAULT_FEATURE_MODE,
    DEFAULT_FIXED_TEMPERATURE_VALUE,
    DEFAULT_GAME_SEGMENT_LENGTH,
    DEFAULT_DISCOUNT_FACTOR,
    DEFAULT_N_EPISODE,
    DEFAULT_N_EVALUATOR_EPISODE,
    DEFAULT_NUM_UNROLL_STEPS,
    DEFAULT_NUM_SIMULATIONS,
    DEFAULT_PONG_EPISODE_MAX_STEPS,
    DEFAULT_PONG_RESET_PRESSURE_AGENT,
    DEFAULT_PONG_RESET_PROFILE,
    DEFAULT_RANDOM_COLLECT_EPISODE_NUM,
    DEFAULT_REWARD_SUPPORT_DELTA,
    DEFAULT_REWARD_SUPPORT_MAX,
    DEFAULT_REWARD_SUPPORT_MIN,
    DEFAULT_SEED,
    DEFAULT_SUPPORT_SCALE,
    DEFAULT_TD_STEPS,
    DEFAULT_UPDATE_PER_COLLECT,
    DEFAULT_VALUE_SUPPORT_DELTA,
    DEFAULT_VALUE_SUPPORT_MAX,
    DEFAULT_VALUE_SUPPORT_MIN,
)
from curvyzero.infra.modal.lightzero_dummy_pong_tiny_train_smoke import (
    RUNS_MOUNT,
    _run_lightzero_dummy_pong_tiny_train_smoke,
    image,
    runs_volume,
)

APP_NAME = "curvyzero-lightzero-dummy-pong-train-attempt"
DEFAULT_MAX_ENV_STEP = 512
DEFAULT_MAX_TRAIN_ITER = 8
MAX_ALLOWED_ENV_STEP = 8192
MAX_ALLOWED_TRAIN_ITER = 64

app = modal.App(APP_NAME)


@app.function(image=image, volumes={str(RUNS_MOUNT): runs_volume}, timeout=20 * 60)
def lightzero_dummy_pong_train_attempt(
    mode: str = "progression",
    env: str = DEFAULT_ENV,
    feature_mode: str = DEFAULT_FEATURE_MODE,
    seed: int = DEFAULT_SEED,
    opponent_policy: str = "random_uniform",
    ego_agent: str = "player_0",
    opponent_checkpoint: str | None = None,
    opponent_checkpoint_label: str | None = None,
    opponent_checkpoint_adapter: str | None = None,
    opponent_checkpoint_num_simulations: int | None = None,
    opponent_checkpoint_state_key: str | None = None,
    max_env_step: int = DEFAULT_MAX_ENV_STEP,
    pong_episode_max_steps: int | None = DEFAULT_PONG_EPISODE_MAX_STEPS,
    pong_reset_profile: str = DEFAULT_PONG_RESET_PROFILE,
    pong_reset_pressure_agent: str = DEFAULT_PONG_RESET_PRESSURE_AGENT,
    max_train_iter: int = DEFAULT_MAX_TRAIN_ITER,
    collector_env_num: int = DEFAULT_COLLECTOR_ENV_NUM,
    evaluator_env_num: int = DEFAULT_EVALUATOR_ENV_NUM,
    n_evaluator_episode: int = DEFAULT_N_EVALUATOR_EPISODE,
    num_simulations: int = DEFAULT_NUM_SIMULATIONS,
    batch_size: int = DEFAULT_BATCH_SIZE,
    update_per_collect: int = DEFAULT_UPDATE_PER_COLLECT,
    n_episode: int = DEFAULT_N_EPISODE,
    game_segment_length: int = DEFAULT_GAME_SEGMENT_LENGTH,
    random_collect_episode_num: int = DEFAULT_RANDOM_COLLECT_EPISODE_NUM,
    eps_greedy_exploration_in_collect: bool = DEFAULT_EPS_GREEDY_EXPLORATION_IN_COLLECT,
    eps_start: float = DEFAULT_EPS_START,
    eps_end: float = DEFAULT_EPS_END,
    eps_decay: int = DEFAULT_EPS_DECAY,
    fixed_temperature_value: float = DEFAULT_FIXED_TEMPERATURE_VALUE,
    td_steps: int | None = DEFAULT_TD_STEPS,
    num_unroll_steps: int | None = DEFAULT_NUM_UNROLL_STEPS,
    discount_factor: float | None = DEFAULT_DISCOUNT_FACTOR,
    support_scale: int | None = DEFAULT_SUPPORT_SCALE,
    reward_support_min: float | None = DEFAULT_REWARD_SUPPORT_MIN,
    reward_support_max: float | None = DEFAULT_REWARD_SUPPORT_MAX,
    reward_support_delta: float | None = DEFAULT_REWARD_SUPPORT_DELTA,
    value_support_min: float | None = DEFAULT_VALUE_SUPPORT_MIN,
    value_support_max: float | None = DEFAULT_VALUE_SUPPORT_MAX,
    value_support_delta: float | None = DEFAULT_VALUE_SUPPORT_DELTA,
    run_id: str | None = None,
    attempt_id: str | None = None,
) -> dict[str, Any]:
    return _run_lightzero_dummy_pong_tiny_train_smoke(
        mode=mode,
        env=env,
        feature_mode=feature_mode,
        seed=seed,
        opponent_policy=opponent_policy,
        ego_agent=ego_agent,
        opponent_checkpoint=opponent_checkpoint,
        opponent_checkpoint_label=opponent_checkpoint_label,
        opponent_checkpoint_adapter=opponent_checkpoint_adapter,
        opponent_checkpoint_num_simulations=opponent_checkpoint_num_simulations,
        opponent_checkpoint_state_key=opponent_checkpoint_state_key,
        max_env_step=max_env_step,
        pong_episode_max_steps=pong_episode_max_steps,
        pong_reset_profile=pong_reset_profile,
        pong_reset_pressure_agent=pong_reset_pressure_agent,
        max_train_iter=max_train_iter,
        collector_env_num=collector_env_num,
        evaluator_env_num=evaluator_env_num,
        n_evaluator_episode=n_evaluator_episode,
        num_simulations=num_simulations,
        batch_size=batch_size,
        update_per_collect=update_per_collect,
        n_episode=n_episode,
        game_segment_length=game_segment_length,
        random_collect_episode_num=random_collect_episode_num,
        eps_greedy_exploration_in_collect=eps_greedy_exploration_in_collect,
        eps_start=eps_start,
        eps_end=eps_end,
        eps_decay=eps_decay,
        fixed_temperature_value=fixed_temperature_value,
        td_steps=td_steps,
        num_unroll_steps=num_unroll_steps,
        discount_factor=discount_factor,
        support_scale=support_scale,
        reward_support_min=reward_support_min,
        reward_support_max=reward_support_max,
        reward_support_delta=reward_support_delta,
        value_support_min=value_support_min,
        value_support_max=value_support_max,
        value_support_delta=value_support_delta,
        run_id=run_id,
        attempt_id=attempt_id,
        max_allowed_env_step=MAX_ALLOWED_ENV_STEP,
        max_allowed_train_iter=MAX_ALLOWED_TRAIN_ITER,
        job_kind="lightzero_custom_dummy_pong_muzero_train_attempt",
        result_label="LightZero custom-env dummy Pong MuZero scaled train attempt",
    )


@app.local_entrypoint()
def main(
    mode: str = "progression",
    env: str = DEFAULT_ENV,
    feature_mode: str = DEFAULT_FEATURE_MODE,
    seed: int = DEFAULT_SEED,
    opponent_policy: str = "random_uniform",
    ego_agent: str = "player_0",
    opponent_checkpoint: str | None = None,
    opponent_checkpoint_label: str | None = None,
    opponent_checkpoint_adapter: str | None = None,
    opponent_checkpoint_num_simulations: int | None = None,
    opponent_checkpoint_state_key: str | None = None,
    max_env_step: int = DEFAULT_MAX_ENV_STEP,
    pong_episode_max_steps: int | None = DEFAULT_PONG_EPISODE_MAX_STEPS,
    pong_reset_profile: str = DEFAULT_PONG_RESET_PROFILE,
    pong_reset_pressure_agent: str = DEFAULT_PONG_RESET_PRESSURE_AGENT,
    max_train_iter: int = DEFAULT_MAX_TRAIN_ITER,
    collector_env_num: int = DEFAULT_COLLECTOR_ENV_NUM,
    evaluator_env_num: int = DEFAULT_EVALUATOR_ENV_NUM,
    n_evaluator_episode: int = DEFAULT_N_EVALUATOR_EPISODE,
    num_simulations: int = DEFAULT_NUM_SIMULATIONS,
    batch_size: int = DEFAULT_BATCH_SIZE,
    update_per_collect: int = DEFAULT_UPDATE_PER_COLLECT,
    n_episode: int = DEFAULT_N_EPISODE,
    game_segment_length: int = DEFAULT_GAME_SEGMENT_LENGTH,
    random_collect_episode_num: int = DEFAULT_RANDOM_COLLECT_EPISODE_NUM,
    eps_greedy_exploration_in_collect: bool = DEFAULT_EPS_GREEDY_EXPLORATION_IN_COLLECT,
    eps_start: float = DEFAULT_EPS_START,
    eps_end: float = DEFAULT_EPS_END,
    eps_decay: int = DEFAULT_EPS_DECAY,
    fixed_temperature_value: float = DEFAULT_FIXED_TEMPERATURE_VALUE,
    td_steps: int | None = DEFAULT_TD_STEPS,
    num_unroll_steps: int | None = DEFAULT_NUM_UNROLL_STEPS,
    discount_factor: float | None = DEFAULT_DISCOUNT_FACTOR,
    support_scale: int | None = DEFAULT_SUPPORT_SCALE,
    reward_support_min: float | None = DEFAULT_REWARD_SUPPORT_MIN,
    reward_support_max: float | None = DEFAULT_REWARD_SUPPORT_MAX,
    reward_support_delta: float | None = DEFAULT_REWARD_SUPPORT_DELTA,
    value_support_min: float | None = DEFAULT_VALUE_SUPPORT_MIN,
    value_support_max: float | None = DEFAULT_VALUE_SUPPORT_MAX,
    value_support_delta: float | None = DEFAULT_VALUE_SUPPORT_DELTA,
    run_id: str | None = None,
    attempt_id: str | None = None,
) -> None:
    result = lightzero_dummy_pong_train_attempt.remote(
        mode=mode,
        env=env,
        feature_mode=feature_mode,
        seed=seed,
        opponent_policy=opponent_policy,
        ego_agent=ego_agent,
        opponent_checkpoint=opponent_checkpoint,
        opponent_checkpoint_label=opponent_checkpoint_label,
        opponent_checkpoint_adapter=opponent_checkpoint_adapter,
        opponent_checkpoint_num_simulations=opponent_checkpoint_num_simulations,
        opponent_checkpoint_state_key=opponent_checkpoint_state_key,
        max_env_step=max_env_step,
        pong_episode_max_steps=pong_episode_max_steps,
        pong_reset_profile=pong_reset_profile,
        pong_reset_pressure_agent=pong_reset_pressure_agent,
        max_train_iter=max_train_iter,
        collector_env_num=collector_env_num,
        evaluator_env_num=evaluator_env_num,
        n_evaluator_episode=n_evaluator_episode,
        num_simulations=num_simulations,
        batch_size=batch_size,
        update_per_collect=update_per_collect,
        n_episode=n_episode,
        game_segment_length=game_segment_length,
        random_collect_episode_num=random_collect_episode_num,
        eps_greedy_exploration_in_collect=eps_greedy_exploration_in_collect,
        eps_start=eps_start,
        eps_end=eps_end,
        eps_decay=eps_decay,
        fixed_temperature_value=fixed_temperature_value,
        td_steps=td_steps,
        num_unroll_steps=num_unroll_steps,
        discount_factor=discount_factor,
        support_scale=support_scale,
        reward_support_min=reward_support_min,
        reward_support_max=reward_support_max,
        reward_support_delta=reward_support_delta,
        value_support_min=value_support_min,
        value_support_max=value_support_max,
        value_support_delta=value_support_delta,
        run_id=run_id,
        attempt_id=attempt_id,
    )
    print(json.dumps(result, indent=2, sort_keys=True))
